"""Load and validate organization configuration from config.json."""

from __future__ import annotations

import json
import logging
import shutil
from pathlib import Path
from typing import Any

log = logging.getLogger(__name__)

APP_DIR = Path(__file__).parent
CONFIG_FILE = APP_DIR / "config.json"
CONFIG_EXAMPLE = APP_DIR / "config.example.json"

_OPTION_GROUPS = ("hardware", "software", "portals", "mailboxes")
_config: dict[str, Any] | None = None


def init_config() -> None:
    """Ensure config.json exists, then load it into memory."""
    if not CONFIG_FILE.exists():
        if not CONFIG_EXAMPLE.exists():
            raise RuntimeError(
                f"Missing {CONFIG_EXAMPLE.name}. Cannot start OnboardKit."
            )
        shutil.copy(CONFIG_EXAMPLE, CONFIG_FILE)
        log.info("Created %s from %s", CONFIG_FILE.name, CONFIG_EXAMPLE.name)

    global _config
    _config = _load_and_validate(CONFIG_FILE.read_text(encoding="utf-8"))


def get_config() -> dict[str, Any]:
    if _config is None:
        init_config()
    return _config


def _load_and_validate(raw: str) -> dict[str, Any]:
    data = json.loads(raw)

    if "branding" not in data or "app_name" not in data["branding"]:
        raise ValueError("config.json must include branding.app_name")

    offices = data.get("offices", [])
    if not offices:
        raise ValueError("config.json must include at least one office")

    groups = data.get("option_groups", {})
    for name in _OPTION_GROUPS:
        items = groups.get(name, [])
        if not items:
            raise ValueError(f"config.json option_groups.{name} must not be empty")
        seen: set[str] = set()
        for item in items:
            opt_id = item.get("id")
            if not opt_id:
                raise ValueError(f"Each {name} option needs an id")
            if opt_id in seen:
                raise ValueError(f"Duplicate {name} id: {opt_id}")
            seen.add(opt_id)

    return data


def get_branding() -> dict[str, str]:
    branding = dict(get_config().get("branding", {}))
    branding.setdefault("app_name", "OnboardKit")
    branding.setdefault("tagline", "")
    branding.setdefault("it_team_label", "IT Team")
    branding.setdefault("email_subject_prefix", "New Hire IT Request")
    branding.setdefault(
        "email_footer",
        "Generated by OnboardKit. Reply with any questions.",
    )
    return branding


def get_offices() -> list[str]:
    return list(get_config().get("offices", []))


def get_alarm_facilities() -> list[tuple[str, str]]:
    """Return (id, label) pairs for alarm facility checkboxes."""
    items = get_config().get("alarm_facilities", [])
    result: list[tuple[str, str]] = []
    for item in items:
        if isinstance(item, str):
            slug = item.lower().replace(" ", "_")
            result.append((slug, item))
        else:
            result.append((item["id"], item["label"]))
    return result


def get_option_tuples(group: str) -> list[tuple[str, str]]:
    items = get_config().get("option_groups", {}).get(group, [])
    return [(item["id"], item["label"]) for item in items]


def get_option_labels(group: str) -> dict[str, str]:
    return dict(get_option_tuples(group))


def get_placeholders() -> dict[str, str]:
    return dict(get_config().get("placeholders", {}))


def employee_field_enabled(field: str) -> bool:
    fields = get_config().get("employee_fields", {})
    return bool(fields.get(field, {}).get("enabled", False))


def employee_field_label(field: str, default: str) -> str:
    fields = get_config().get("employee_fields", {})
    return str(fields.get(field, {}).get("label", default))


def get_preset_flags() -> list[dict[str, str]]:
    return list(get_config().get("preset_flags", []))


def get_role_followup() -> dict[str, Any] | None:
    followup = get_config().get("role_followup", {})
    if not followup.get("enabled"):
        return None
    return followup


def preset_triggers_followup(preset: dict) -> bool:
    followup = get_role_followup()
    if not followup:
        return False
    flag = followup.get("preset_flag", "role_followup")
    return bool(preset.get(flag))


def template_context() -> dict[str, Any]:
    """Common Jinja context for wizard and admin templates."""
    branding = get_branding()
    return {
        "app_name": branding["app_name"],
        "tagline": branding.get("tagline", ""),
        "it_team_label": branding["it_team_label"],
        "offices": get_offices(),
        "alarm_facilities": get_alarm_facilities(),
        "hardware_options": get_option_tuples("hardware"),
        "software_options": get_option_tuples("software"),
        "portal_options": get_option_tuples("portals"),
        "mailbox_options": get_option_tuples("mailboxes"),
        "placeholders": get_placeholders(),
        "employee_fields": get_config().get("employee_fields", {}),
        "preset_flags": get_preset_flags(),
        "role_followup": get_role_followup(),
    }
